name: "AI Code Review Action"
description: "Perform code reviews and comment on diffs using OLLAMA API."
inputs:
  GITHUB_TOKEN:
    description: "GitHub token to interact with the repository."
    required: true
  API_MODEL:
    description: "OLLAMA API model."
    required: false
    default: "llama2:7b"
  exclude:
    description: "Glob patterns to exclude files from the diff analysis"
    required: false
    default: ""
runs:
  using: "node16"
  main: "dist/index.js"
branding:
  icon: "aperture"
  color: "green"
